stages:
  - build

.stack-build:
  stage: build
  script:
  - ./stack-build -n $STACK_RECIPE -s $STACK_SYSTEM -r $STACK_RECIPE
  after_script:
  - rm -Rf /dev/shm/jenkssl

build-mc:
  tags: [hohgant-container]
  stage: build
  variables:
    CSCS_RUN_BARE_METAL: 'YES'
    SLURM_JOB_NUM_NODES: 1
    SLURM_TIMELIMIT: '03:00:00'
    PULL_IMAGE: 'NO'
    SLURM_PARTITION: cpu
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - ./stack-build -n arbor-mc -s hohgant -r $(pwd)/recipes/arbor/multicore

  # cleanup, runs always, independent of `script` exit status
  after_script:
    - rm -Rf /dev/shm/jenkssl

build-zinal-test:
  extends: .stack-build
  tags: [zinal-spack-stack-builder]
  variables:
    SLURM_TIMELIMIT: 180
    STACK_NAME: arbor-mc
    STACK_SYSTEM: hohgant
    STACK_RECIPE: recipes/arbor/multicore
