stages:
  - build

.stack-build:
  stage: build
  script:
  - ./stack-build -n $STACK_RECIPE -s $STACK_SYSTEM -r $STACK_RECIPE
  after_script:
  - rm -Rf /dev/shm/jenkssl

build-mc:
  extends: .stack-build
  tags: [hohgant-spack-stack-builder]
  variables:
    SLURM_TIMELIMIT: 180
    STACK_NAME: arbor-mc
    STACK_SYSTEM: hohgant
    STACK_RECIPE: recipes/arbor/multicore
