stages:
  - build

build stack:
  tags: [hohgant-container]
  script:
    - BUILD_PATH=/dev/shm/jenkssl/spack-stack-pe-dft
    - RECIPE_PATH=$PWD/pe-dft
    - PYTHON_VENV=/dev/shm/jenkssl/venv
    - python3 -m venv $PYTHON_VENV
    - source $PYTHON_VENV/bin/activate
    - pip install -r sstool/requirements.txt
    - env --chdir=sstool ./bin/sstool -b$BUILD_PATH -r$RECIPE_PATH -d
    - env --chdir="$BUILD_PATH" --ignore-environment PATH=/usr/bin:/bin:$PWD/spack/bin make modules store.squashfs -j64
  stage: build
  variables:
    CSCS_RUN_BARE_METAL: 'YES'
    SLURM_JOB_NUM_NODES: 1
    PULL_IMAGE: 'NO'
    SLURM_PARTITION: cpu
    GIT_SUBMODULE_STRATEGY: recursive
