stages:
  - build

build stack:
  tags: [hohgant-container]
  script:
    - BUILD_PATH=/dev/shm/jenkssl/spack-stack-pe-dft
    - RECIPE_PATH=pe-dft
    - sstool/bin/sstool -b$BUILD_PATH -r$RECIPE_PATH -d
    - cd "$BUILD_PATH"
    - env --ignore-environment PATH=/usr/bin:/bin:$PWD/spack/bin make modules store.squashfs -j64
